# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-12-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=60)),
                ('amountneeded', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amountraised', models.DecimalField(decimal_places=2, max_digits=8)),
                ('picture', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('amountcontributed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contributiondate', models.DateTimeField()),
                ('contributedto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtview.Budgets')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('opponentschool', models.CharField(max_length=60)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=60)),
                ('grade', models.IntegerField()),
                ('weightclass', models.IntegerField()),
                ('bio', models.TextField()),
                ('instagram', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
