# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2018-01-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtview', '0002_auto_20171226_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMerchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60)),
                ('spiritpack', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('picture', models.CharField(max_length=60)),
                ('sizes', models.CharField(choices=[('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('XXL', 'XXL')], default='MEDIUM', max_length=14)),
                ('colors', models.CharField(choices=[('White', 'White'), ('Navy', 'Navy'), ('Green', 'Green')], default='White', max_length=14)),
            ],
        ),
    ]
