# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2018-01-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtview', '0003_storemerchandise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemerchandise',
            name='colors',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='storemerchandise',
            name='sizes',
            field=models.CharField(max_length=14),
        ),
    ]
